eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8780/eureka/
server:
  port: 8791
spring:
  application:
    name: impala
impala:
  impala_host: quickstart.cloudera
  impala_port: 21050
  impala_username: hive